### ISSUE TITLE
[疑似BUG] 使用 .r 指令骰默认骰子时，面数不显示

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-plan#139]
我的默认骰子是D100，用 `.r` 骰默认骰，在表达式文本中没有显示面数

> .r 原因
> 为了原因，\<JohNSoN\>掷出了 d=82

> .r d 原因
> 为了原因，\<JohNSoN\>掷出了 d=76

> .r d100 原因
> 为了原因，\<JohNSoN\>掷出了 d100=50

> .r d+10 原因
> 为了原因，\<JohNSoN\>掷出了 d+10=1 + 10=11

**Comment by lxy071130** [comment]
这个pr是不是可以close了？
