### ISSUE TITLE
[BUG] KOOK 中部分带计算的指令识别错误

### ISSUE THREAD

**Issue by Verplitic** [sealdice/sealdice-plan#140]
在 KOOK 的网页端，带有星号(*)的投骰计算指令不会被识别，如图片：

![web_error](https://user-images.githubusercontent.com/57583509/223366760-6f0e1c29-ec92-405a-b8f8-17cdc18dd9d7.png)

而在手机端（iOS），星号会被转义为 Markdown：

![client_error](https://user-images.githubusercontent.com/57583509/223367862-9caaa6f3-dfc8-4ec9-8321-6004c9f6b303.jpeg)

因为设备限制，没法测试所有客户端。推测这是 KOOK 对 Markdown 记号的处理导致的，不知道海豹这边能不能解决。

关于 Markdown 转义，不知道 Discord 有没有此问题。现在没有条件测试。

**Comment by Verplitic** [comment]
# 追加：测试后发现更多转义问题

总而言之，网页版和 Windows 端的 KOOK 会将所有 Markdown 标记转义，包括自带的 (spl)、(emj) 标记。

- 特别地，在网页端，两个短横(--)会被加上反斜杠转义，这将导致 Kwarg 不可识别，指令解析出错：
<img width="152" alt="短横（后台截图）" src="https://user-images.githubusercontent.com/57583509/224071963-2762f9bc-ec78-4719-8587-feaa4c608351.png">

**Comment by Szzrain** [comment]
完成 [25b6383](https://github.com/sealdice/sealdice-core/commit/25b6383bd665dc93f2cd58391bb10686fc2e9d3b)
