### ISSUE TITLE
[Request] 自动更新后清理auto_update可执行文件和update目录

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-plan#172]
如题，为了保持工作目录清洁，请考虑在更新后清理更新中用到的文件

**Comment by Szzrain** [comment]
@fy0 如果正常升级是会清理的吧

**Comment by Szzrain** [comment]
海豹会在自动更新后清理auto update 文件夹，如果你的没有被清理，请提交bug issue

**Comment by Xiangze-Li** [comment]
感谢回复，我会先手动清理，下次更新再观察下

**Comment by fy0** [comment]
有清理的，话说你是什么系统，会不会是特定OS上触发的bug？
