### ISSUE TITLE
[Request] 代骰.r和.rd指令

### ISSUE THREAD

**Issue by asterson** [sealdice/sealdice-plan#184]
当我尝试`.r手枪@群友` 时，骰子没有任何回复，日志显示忽略指令了。而`.ra手枪@群友`会正常代骰，可以确认群友并没有被识别为机器人，但我需要的值会作为目标值出现在比较里。
`.rd20+加值@群友` 这样的指令也不会回复

听说是因为有人希望.rd不会触发代骰以便和其他骰子机器人一起使用而采取的设计，那我提议一个.rs指令作为替代，取substitute的含义

**描述你想要的解决方案**
希望`。rs手枪@群友`和`。rsd20+加值@群友`这类指令能直接代骰群友录入的数据

**Comment by asterson** [comment]
指令前缀s在日本的骰子机器人bcdice里有暗骰的用法，可能是secret的意思。但是中国的骰子的暗骰指令用的是h，我就大着胆子提了用s表示代骰。不知道这个主意好不好，姑且提一下相关情况以便参考

**Comment by fy0** [comment]
可以，之前有一个类似作用的指令，叫做rx 之后版本把他接入代骰

**Comment by fy0** [comment]
已实现，1.2.5版本可用
