### ISSUE TITLE
[Request] 使helpdoc加载失败的报错普通骰主可读

### ISSUE THREAD

**Issue by lxy071130** [sealdice/sealdice-plan#187]
**你的功能请求是否与一个问题有关？请描述。**
当一个helpdoc加载失败时，它返回这样的信息：  
[![58df12669a67e909.png](https://i.postimg.cc/wTHsPqHj/58df12669a67e909.png)](https://postimg.cc/t7STnHYK)

**描述你想要的解决方案**
如题，使helpdoc加载失败的报错普通骰主可读。可能的示例:
`parse error near linex, symbol xxx unexpected`

**Comment by fy0** [comment]
这个触发条件是什么？情况太多了，不一定是文本几行几列无法解析。
这里就是一个下标越界，感觉很难想象

**Comment by Szzrain** [comment]
需要更多信息
