### ISSUE TITLE
[Request] help输出的内容应经过rollvm格式化

### ISSUE THREAD

**Issue by lxy071130** [sealdice/sealdice-plan#189]
**你的功能请求是否与一个问题有关？请描述。**
当我尝试在他人help骰主的时候对他sc（来自一位群友的创意）时，海豹直接返回代码块文本。

**描述你想要的解决方案**
返回rollvm格式化后的文本。

**描述你考虑过的替代方案**
没有想到

**Comment by fy0** [comment]
可能不是太行，对兼容性的影响，不可估量
